@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soullery.extension.shield;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;