@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soullery.extension.soulpower;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;