package lych.soullery.entity;

public class ModEntityNames {
    public static final String CLONED_SKELETON_KING = "cloned_skeleton_king";
    public static final String COMPUTER_SCIENTIST = "computer_scientist";
    public static final String DARK_EVOKER = "dark_evoker";
    public static final String DROPPING_MORTAR_SHELL = "dropping_mortar_shell";
    public static final String ENERGIZED_BLAZE = "energized_blaze";
    public static final String ENGINEER = "engineer";
    public static final String ETHE_ARMORER = "ethe_armorer";
    public static final String ETHEREAL_ARROW = "ethereal_arrow";
    public static final String FANGS = "fangs";
    public static final String FANGS_SUMMONER = "fangs_summoner";
    public static final String FORTIFIED_SOUL_CRYSTAL = "fortified_soul_crystal";
    public static final String GIANT_X = "giant_x";
    public static final String GRAVITATIONAL_DRAGON_FIREBALL = "gravitational_dragon_fireball";
    public static final String HORCRUX = "horcrux";
    public static final String ILLUSORY_HORSE = "illusory_horse";
    public static final String META8 = "meta8";
    public static final String PURSUER = "pursuer";
    public static final String REDSTONE_BOMB = "redstone_bomb";
    public static final String REDSTONE_MORTAR = "redstone_mortar";
    public static final String REDSTONE_TURRET = "redstone_turret";
    public static final String RISING_MORTAR_SHELL = "rising_mortar_shell";
    public static final String ROBOT = "robot";
    public static final String SKELETON_FOLLOWER = "skeleton_follower";
    public static final String SKELETON_KING = "skeleton_king";
    public static final String SOULBALL = "soulball";
    public static final String SOUL_ARROW = "soul_arrow";
    public static final String SOUL_BOLT = "soul_bolt";
    public static final String SOUL_CONTROLLER = "soul_controller";
    public static final String SOUL_CRYSTAL = "soul_crystal";
    public static final String SOUL_DRAGON = "soul_dragon";
    public static final String SOUL_RABBIT = "soul_rabbit";
    public static final String SOUL_SKELETON = "soul_skeleton";
    public static final String SOUL_SKELETON_KING = "soul_skeleton_king";
    public static final String SUB_ZOMBIE = "sub_zombie";
    public static final String VOID_ALCHEMIST = "void_alchemist";
    public static final String VOID_ARCHER = "void_archer";
    public static final String VOID_DEFENDER = "void_defender";
    public static final String VOIDWALKER = "voidwalker";
    public static final String WANDERER = "wanderer";
}
