@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soullery.extension.control.rotation;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;