@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soullery.extension.highlight;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;