@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soullery.util.redirectable;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;