@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soullery.extension.soulpower.debuff;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;